/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package azul;

import org.junit.jupiter.api.BeforeEach;

class BagTest {

    Bag bag;

    @BeforeEach
    void init() {
        bag = new Bag();
    }


}
