/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package azul;

public class App {

    public static void main(String[] args) {}

    public String getGreeting() {
        System.out.println("Hello!");
        return ("app should have a greeting");
    }
}
