/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package azul;

import java.util.ArrayList;
import java.util.List;

public class App {

    public static void main(String[] args) {

    }

    enum Color {
        White,
        Red,
        Green,
        Blue,
        Yellow,
        FirstPlayer
    }

    class Tile {

        private Color color;

        public Tile(Color color) {
            this.color = color;
        }

        public Color getColor() {
            return color;
        }

        public boolean equals(Color gotColor) {
            return gotColor == color;
        }
    }

    class Row {
        private Color color;
        private byte number;

        public Color getColor() {
            return color;
        }

        public byte getNumber() {
            return number;
        }
    }

    class Player {
        private Tile[][] wall = new Tile[5][5];
        private Row[] patternWall = new Row[5];
        private Tile[] floor = new Tile[7];
        private byte points;

        public boolean firstFromMiddle;

        public Tile[][] getWall() {
            return wall;
        }

        public Row[] getPatternWall() {
            return patternWall;
        }

        public Tile[] getFloor() {
            return floor;
        }

        public byte getPoints() {
            return points;
        }

        public byte compareTo(Player other) {
            // compares this players point to the other players point TODO discuss return
            // values
            return 1;
        }

        public boolean addToPatternWall(byte rowNum, Tile[] tiles) {
            // adds Tiles to patternwall and returns if it was successful
            return true;
        }
    }

    class Bag {
        private Tile[] tiles = new Tile[100];

        public Tile[] getTiles() {
            return tiles;
        }

        public Tile[] popTiles() {
            return new Tile[0];
        }
    }

    abstract class TileHolder {

        // átírtam addtilesra, mert ugye, amikor először teszünk rá tileokat, akkor is
        // kvázi a 0 Tile mellé rakunk 5-öt,
        // viszont utána, amikor feltöltjük és volt már három, akkor ugye csak 2-t
        // rakunk mellé
        public abstract void addTiles(Tile[] tiles);

        public abstract Tile[] getTiles();

        public abstract Tile[] popTiles(Color color);

    }

    class ManufactureDisk extends TileHolder {
        private Tile[] tiles = new Tile[5];

        public ManufactureDisk() {
            for (int i = 0; i < tiles.length; i++) {
                tiles[i] = null;
            }
        }

        public void addTiles(Tile[] tiles) {
            if (this.tiles.length + tiles.length <= 5) {
                byte counter = 0;
                for (int i = 0; i < tiles.length; i++) {
                    if (this.tiles[i] == null) {
                        this.tiles[i] = tiles[counter];
                        counter++;
                    }
                }
                if (counter != this.tiles.length - 1) {
                    throw new Error("Some semantical error happened in the code...");
                }
            } else {
                throw new Error("Cannot add this much Tile.");
            }
        }

        public Tile[] getTiles() {
            return tiles;
        }

        public Tile[] popTiles(Color color) {
            byte size = 0;
            for (int i = 0; i < tiles.length; i++) {
                if (tiles[i].color == color) {
                    size++;
                }
            }
            Tile[] tempTiles = new Tile[size];
            byte counter = 0;
            for (int i = 0; i < tiles.length; i++) {
                if (tiles[i].color == color) {
                    tempTiles[counter] = new Tile(color);
                    counter++;
                    tiles[i] = null;
                }
            }
            return tempTiles;
        }
    }

    class Middle extends TileHolder {
        private ArrayList<Tile> tiles = new ArrayList<>() ;

        public void addTiles(Tile[] tiles) {
            for (int i = 0; i < tiles.length; i++) {
                this.tiles.add(tiles[i]);
            }
        }

        public Tile[] getTiles() {
            Tile[] tempTiles = new Tile[tiles.size()];
            for (int i = 0; i < tiles.size(); i++) {
                tempTiles[i]=tiles.get(i);
            }
            return tempTiles;
        }

        public Tile[] popTiles(Color color) {
            byte size = 0;
            for (int i = 0; i < tiles.size(); i++) {
                if (tiles.get(i).color == color) {
                    size++;
                }
            }
            Tile[] tempTiles = new Tile[size];
            byte counter = 0;
            for (int i = 0; i < tiles.size(); i++) {
                if (tiles.get(i).color == color) {
                    tempTiles[counter] = new Tile(color);
                    counter++;
                    tiles.remove(i);
                }
            }
            return tempTiles;
        }
    }

    class GameEngine {
        private Bag bag;
        private Middle middle;
        private ManufactureDisk[] manufactureDisks;
        private Player[] players;
        public byte startingPlayerIndex;
        public byte actualPlayerIndex;

        public void shuffleTo(ManufactureDisk[] disks) {

        }

        private int evaluatePlayer() {
            return 0;
        }

        public Player[] getPlayers() {
            return players;
        }

        public ManufactureDisk[] getManufactureDisks() {
            return manufactureDisks;
        }

        public Middle getMiddle() {
            return middle;
        }

        public Bag getBag() {
            return bag;
        }

        public void init() {

        }

        public void startGame() {

        }

        public Player getWinner() {
            return new Player();
        }

        public Player getCurrentPlayer() {
            return new Player();
        }

        public boolean checkWin() {
            return true;
        }
    }
}
